model_name=SOFTSsharp

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_12 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 12 \
  --e_layers 4 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 512 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 30 \
  --patience 3 \
  --use_norm 0 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_24 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 24 \
  --e_layers 4 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 512 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 30 \
  --patience 3 \
  --use_norm 0 \
  --itr 1


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_48 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 48 \
  --e_layers 4 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 512 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 30 \
  --patience 3 \
  --use_norm 0 \
  --itr 1


python -u run.py \
  --is_training 1 \
  --root_path ./dataset/PEMS/ \
  --data_path PEMS03.npz \
  --model_id PEMS03_96_96 \
  --model $model_name \
  --data PEMS \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 4 \
  --enc_in 358 \
  --dec_in 358 \
  --c_out 358 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 512 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 30 \
  --patience 3 \
  --use_norm 0 \
  --itr 1