model_name=SOFTSsharp

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_96 \
  --model $model_name \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 128 \
  --d_core 64 \
  --d_ff 128 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 3 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_192 \
  --model $model_name \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 128 \
  --d_core 64 \
  --d_ff 128 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 3 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_336 \
  --model $model_name \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 128 \
  --d_core 64 \
  --d_ff 128 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 3 \
  --des 'Exp' \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/ETT-small/ \
  --data_path ETTh2.csv \
  --model_id ETTh2_96_720 \
  --model $model_name \
  --data ETTh2 \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --enc_in 7 \
  --dec_in 7 \
  --c_out 7 \
  --d_model 128 \
  --d_core 64 \
  --d_ff 128 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 20 \
  --patience 3 \
  --des 'Exp' \
  --itr 1