model_name=SOFTSsharp

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_96 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 96 \
  --e_layers 2 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 10 \
  --patience 10 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_192 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 192 \
  --e_layers 2 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 10 \
  --patience 10 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_336 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 336 \
  --e_layers 2 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 10 \
  --patience 10 \
  --itr 1

python -u run.py \
  --is_training 1 \
  --root_path ./dataset/Solar/ \
  --data_path solar_AL.txt \
  --model_id solar_96_720 \
  --model $model_name \
  --data Solar \
  --features M \
  --seq_len 96 \
  --pred_len 720 \
  --e_layers 2 \
  --enc_in 137 \
  --dec_in 137 \
  --c_out 137 \
  --des 'Exp' \
  --d_model 512 \
  --d_core 128 \
  --d_ff 512 \
  --lf_n_heads 2 \
  --lf_dropout 0.1 \
  --lf_attention_dropout 0.1 \
  --lf_initial_threshold 0.5 \
  --lf_use_pos_enc true \
  --learning_rate 0.0003 \
  --lradj cosine \
  --train_epochs 10 \
  --patience 10 \
  --itr 1
